### ISSUE TITLE
ITS / 18S

### ISSUE THREAD

**Issue by sjanssen2** [qiime2/q2-fragment-insertion#10]
**Improvement Description**
Jake asked if it would be possible to compute insertion trees not only for 16S but also for 18S and ITS.

**Comments**
I think that would work in principle, however we would need to create reference trees for the according databases (Silva and Unite). Any comments?

**Comment by wasade** [comment]
18S should be fine, good to benchmark. I'm not aware of an ITS tree that doesn't suck, and I do not believe UNITE exposes a phylogeny. ITS is not conserved and doesn't work for alignments over modest phylogenetic divergence.

**Comment by sjanssen2** [comment]
I remember ITS is relatively structured RNA, do you know if people tried to come up with an alignment based on RNA structure? Would that be worth a short or is that obsolete because we are moving to shotgun anyway?

**Comment by wasade** [comment]
It's not structurally conserved. The alignments are atrocious.

**Comment by sjanssen2** [comment]
Regarding Silva:
@wasade do you think we could go with http://ftp.arb-silva.de/qiime/Silva_128_release.tgz , decorate the tree (`SILVA_128_QIIME_release/trees/99/99_otus.tre`) via tax2tree with taxonomic labels from `SILVA_128_QIIME_release/taxonomy/18S_only/99/consensus_taxonomy_7_levels.txt` and produce a SEPP reference together with the alignment `SILVA_128_QIIME_release/rep_set_aligned/99/99_otus_aligned.fasta.gz` following [Siavash's instructions](https://github.com/smirarab/sepp/tree/master/sepp-package/buildref)?

**Comment by wasade** [comment]
Doesn't the tree they have already contain internal node labels?

**Comment by sjanssen2** [comment]
nope. I checked all node.names, they are either floats or None (referring to SILVA_128_QIIME_release/trees/99/99_otus.tre)

**Comment by wasade** [comment]
It is not safe go decorate the taxonomy on and say its the Silva taxonomy
unfortunately

**Comment by sjanssen2** [comment]
Ok, than we might want to go ahead without taxonomic decoration. We need those only for the `FeatureData[Taxonomy]` output, which you don't like anyway ;-)
In principle, we could also obtain taxonomy by finding the closest reference tip and use this ID to look up linages in classical two column taxonomy files.
