### ISSUE TITLE
Trouble with Silva 128 in classify-otus-experimental ? 

### ISSUE THREAD

**Issue by Rkubinski** [qiime2/q2-fragment-insertion#71]
I ran fragment insertion as seen in the tutorial. I used the Silva 128 provided tree and alignment. My insertion tree was created, and I filtered my feature table. However, once I get to the classify-otus-experimental step and use the Silva 128 consensus 7 level taxonomy, I get the following error: 

Not all OTUs in the provided insertion tree have mappings in the provided reference taxonomy. 
I am attaching my insertion tree. 
Any help would be appreciated!

[insertion-tree.qza.gz](https://github.com/qiime2/q2-fragment-insertion/files/3809769/insertion-tree.qza.gz)

**Comment by thermokarst** [comment]
Hi @Rkubinski - we provide support on the QIIME 2 Forum - https://forum.qiime2.org. Please post your question there, thanks!
