### ISSUE TITLE
qiime phylogeny align-to-tree-mafft-fasttree

### ISSUE THREAD

**Issue by hhxxll2** [qiime2/q2-fragment-insertion#75]
Excuse me, how to solve this problem

Plugin error from phylogeny:

  Command '['mafft', '--preservecase', '--inputorder', '--thread', '33', '/tmp/qiime2-archive-tspmm41w/4dd87431-bf1c-465f-8f38-2d4c3a9605cf/data/dna-sequences.fasta']' returned non-zero exit status 1.

Debug info has been saved to /tmp/qiime2-q2cli-err-6e_xupmi.log

**Comment by thermokarst** [comment]
Hi @hhxxll2! Please visit us at forum.qiime2.org for user support - this issue tracker is for development discussion. Thanks!
