### ISSUE TITLE
ENH: "Preserve" original node names

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-fragment-insertion#78]
**Improvement Description**
"Preserve" original feature IDs by renaming with the `rename-json.py` output by SEPP.

Because SEPP [renames nodes ](https://github.com/smirarab/sepp/blame/master/README.SEPP.md#L109), the trees it produces don't play nice with downstream tools like [Empress](https://github.com/biocore/empress) that can color trees using feature metadata. 

**Current Behavior**
This tree cannot be easily colored by taxonomy, because the node IDs do not map to the original feature IDs.
![image](https://user-images.githubusercontent.com/39198770/121419231-96bc6e80-c920-11eb-93a0-ab36dd709a07.png)

**Proposed Behavior**
Use the `rename-json.py` script output by SEPP to "preserve" original feature IDs, probably by exposing a new parameter so as to not impact runtimes.

**Comment by ChrisKeefe** [comment]
OK, the plot thickens. It looks like _some_ of the nodes in this tree have preserved their original feature IDs. In this zoomed-in shot of the same tree, I've got a QIIME 2 feature-id, and the expected coloring and taxonomy information. 

![image](https://user-images.githubusercontent.com/39198770/121420387-ddf72f00-c921-11eb-9c92-b0c5ef0de558.png)

Not sure why the behavior is inconsistent, but I'll drop a note in here if I run into a good explanation.

**Comment by wasade** [comment]
Hi @ChrisKeefe, placed features should have preserved tip names. The reference tree will also contain the tips for the reference as well, for Greengenes this is another ~200k tips using GG identifiers. Would that explain what you're observing?

**Comment by ChrisKeefe** [comment]
Absolutely does, thanks @wasade ! So the majority of the feature IDs are coming straight out of Silva, and the coloring in Empress is just getting overwhelmed by uncolored reference features not found in our study data.

Setting `--p-shear-to-feature-metadata` takes care of the issue nicely. 
![image](https://user-images.githubusercontent.com/39198770/121435420-b315d680-c933-11eb-8d62-a75b1e310cd6.png)
